/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedNovaFichaIndexRouteImport } from './routes/_authenticated/nova-ficha.index'
import { Route as AuthenticatedFichasIndexRouteImport } from './routes/_authenticated/fichas.index'
import { Route as AuthenticatedNovaFichaSarampoRouteImport } from './routes/_authenticated/nova-ficha.sarampo'
import { Route as AuthenticatedNovaFichaRubeolaRouteImport } from './routes/_authenticated/nova-ficha.rubeola'
import { Route as AuthenticatedNovaFichaFebreAmarelaRouteImport } from './routes/_authenticated/nova-ficha.febre-amarela'
import { Route as AuthenticatedNovaFichaEpizootiaRouteImport } from './routes/_authenticated/nova-ficha.epizootia'
import { Route as AuthenticatedNovaFichaDifteriaRouteImport } from './routes/_authenticated/nova-ficha.difteria'
import { Route as AuthenticatedNovaFichaDengueRouteImport } from './routes/_authenticated/nova-ficha.dengue'
import { Route as AuthenticatedNovaFichaCoquelucheRouteImport } from './routes/_authenticated/nova-ficha.coqueluche'
import { Route as AuthenticatedNovaFichaChikungunyaRouteImport } from './routes/_authenticated/nova-ficha.chikungunya'
import { Route as AuthenticatedFichasSarampoRouteImport } from './routes/_authenticated/fichas.sarampo'
import { Route as AuthenticatedFichasRubeolaRouteImport } from './routes/_authenticated/fichas.rubeola'
import { Route as AuthenticatedFichasFebreAmarelaRouteImport } from './routes/_authenticated/fichas.febre-amarela'
import { Route as AuthenticatedFichasEpizootiaRouteImport } from './routes/_authenticated/fichas.epizootia'
import { Route as AuthenticatedFichasDifteriaRouteImport } from './routes/_authenticated/fichas.difteria'
import { Route as AuthenticatedFichasDengueRouteImport } from './routes/_authenticated/fichas.dengue'
import { Route as AuthenticatedFichasCoquelucheRouteImport } from './routes/_authenticated/fichas.coqueluche'
import { Route as AuthenticatedFichasChikungunyaRouteImport } from './routes/_authenticated/fichas.chikungunya'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNovaFichaIndexRoute =
  AuthenticatedNovaFichaIndexRouteImport.update({
    id: '/nova-ficha/',
    path: '/nova-ficha/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFichasIndexRoute =
  AuthenticatedFichasIndexRouteImport.update({
    id: '/fichas/',
    path: '/fichas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNovaFichaSarampoRoute =
  AuthenticatedNovaFichaSarampoRouteImport.update({
    id: '/nova-ficha/sarampo',
    path: '/nova-ficha/sarampo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNovaFichaRubeolaRoute =
  AuthenticatedNovaFichaRubeolaRouteImport.update({
    id: '/nova-ficha/rubeola',
    path: '/nova-ficha/rubeola',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNovaFichaFebreAmarelaRoute =
  AuthenticatedNovaFichaFebreAmarelaRouteImport.update({
    id: '/nova-ficha/febre-amarela',
    path: '/nova-ficha/febre-amarela',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNovaFichaEpizootiaRoute =
  AuthenticatedNovaFichaEpizootiaRouteImport.update({
    id: '/nova-ficha/epizootia',
    path: '/nova-ficha/epizootia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNovaFichaDifteriaRoute =
  AuthenticatedNovaFichaDifteriaRouteImport.update({
    id: '/nova-ficha/difteria',
    path: '/nova-ficha/difteria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNovaFichaDengueRoute =
  AuthenticatedNovaFichaDengueRouteImport.update({
    id: '/nova-ficha/dengue',
    path: '/nova-ficha/dengue',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNovaFichaCoquelucheRoute =
  AuthenticatedNovaFichaCoquelucheRouteImport.update({
    id: '/nova-ficha/coqueluche',
    path: '/nova-ficha/coqueluche',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNovaFichaChikungunyaRoute =
  AuthenticatedNovaFichaChikungunyaRouteImport.update({
    id: '/nova-ficha/chikungunya',
    path: '/nova-ficha/chikungunya',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFichasSarampoRoute =
  AuthenticatedFichasSarampoRouteImport.update({
    id: '/fichas/sarampo',
    path: '/fichas/sarampo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFichasRubeolaRoute =
  AuthenticatedFichasRubeolaRouteImport.update({
    id: '/fichas/rubeola',
    path: '/fichas/rubeola',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFichasFebreAmarelaRoute =
  AuthenticatedFichasFebreAmarelaRouteImport.update({
    id: '/fichas/febre-amarela',
    path: '/fichas/febre-amarela',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFichasEpizootiaRoute =
  AuthenticatedFichasEpizootiaRouteImport.update({
    id: '/fichas/epizootia',
    path: '/fichas/epizootia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFichasDifteriaRoute =
  AuthenticatedFichasDifteriaRouteImport.update({
    id: '/fichas/difteria',
    path: '/fichas/difteria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFichasDengueRoute =
  AuthenticatedFichasDengueRouteImport.update({
    id: '/fichas/dengue',
    path: '/fichas/dengue',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFichasCoquelucheRoute =
  AuthenticatedFichasCoquelucheRouteImport.update({
    id: '/fichas/coqueluche',
    path: '/fichas/coqueluche',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFichasChikungunyaRoute =
  AuthenticatedFichasChikungunyaRouteImport.update({
    id: '/fichas/chikungunya',
    path: '/fichas/chikungunya',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/fichas/chikungunya': typeof AuthenticatedFichasChikungunyaRoute
  '/fichas/coqueluche': typeof AuthenticatedFichasCoquelucheRoute
  '/fichas/dengue': typeof AuthenticatedFichasDengueRoute
  '/fichas/difteria': typeof AuthenticatedFichasDifteriaRoute
  '/fichas/epizootia': typeof AuthenticatedFichasEpizootiaRoute
  '/fichas/febre-amarela': typeof AuthenticatedFichasFebreAmarelaRoute
  '/fichas/rubeola': typeof AuthenticatedFichasRubeolaRoute
  '/fichas/sarampo': typeof AuthenticatedFichasSarampoRoute
  '/nova-ficha/chikungunya': typeof AuthenticatedNovaFichaChikungunyaRoute
  '/nova-ficha/coqueluche': typeof AuthenticatedNovaFichaCoquelucheRoute
  '/nova-ficha/dengue': typeof AuthenticatedNovaFichaDengueRoute
  '/nova-ficha/difteria': typeof AuthenticatedNovaFichaDifteriaRoute
  '/nova-ficha/epizootia': typeof AuthenticatedNovaFichaEpizootiaRoute
  '/nova-ficha/febre-amarela': typeof AuthenticatedNovaFichaFebreAmarelaRoute
  '/nova-ficha/rubeola': typeof AuthenticatedNovaFichaRubeolaRoute
  '/nova-ficha/sarampo': typeof AuthenticatedNovaFichaSarampoRoute
  '/fichas/': typeof AuthenticatedFichasIndexRoute
  '/nova-ficha/': typeof AuthenticatedNovaFichaIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/': typeof AuthenticatedIndexRoute
  '/fichas/chikungunya': typeof AuthenticatedFichasChikungunyaRoute
  '/fichas/coqueluche': typeof AuthenticatedFichasCoquelucheRoute
  '/fichas/dengue': typeof AuthenticatedFichasDengueRoute
  '/fichas/difteria': typeof AuthenticatedFichasDifteriaRoute
  '/fichas/epizootia': typeof AuthenticatedFichasEpizootiaRoute
  '/fichas/febre-amarela': typeof AuthenticatedFichasFebreAmarelaRoute
  '/fichas/rubeola': typeof AuthenticatedFichasRubeolaRoute
  '/fichas/sarampo': typeof AuthenticatedFichasSarampoRoute
  '/nova-ficha/chikungunya': typeof AuthenticatedNovaFichaChikungunyaRoute
  '/nova-ficha/coqueluche': typeof AuthenticatedNovaFichaCoquelucheRoute
  '/nova-ficha/dengue': typeof AuthenticatedNovaFichaDengueRoute
  '/nova-ficha/difteria': typeof AuthenticatedNovaFichaDifteriaRoute
  '/nova-ficha/epizootia': typeof AuthenticatedNovaFichaEpizootiaRoute
  '/nova-ficha/febre-amarela': typeof AuthenticatedNovaFichaFebreAmarelaRoute
  '/nova-ficha/rubeola': typeof AuthenticatedNovaFichaRubeolaRoute
  '/nova-ficha/sarampo': typeof AuthenticatedNovaFichaSarampoRoute
  '/fichas': typeof AuthenticatedFichasIndexRoute
  '/nova-ficha': typeof AuthenticatedNovaFichaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/fichas/chikungunya': typeof AuthenticatedFichasChikungunyaRoute
  '/_authenticated/fichas/coqueluche': typeof AuthenticatedFichasCoquelucheRoute
  '/_authenticated/fichas/dengue': typeof AuthenticatedFichasDengueRoute
  '/_authenticated/fichas/difteria': typeof AuthenticatedFichasDifteriaRoute
  '/_authenticated/fichas/epizootia': typeof AuthenticatedFichasEpizootiaRoute
  '/_authenticated/fichas/febre-amarela': typeof AuthenticatedFichasFebreAmarelaRoute
  '/_authenticated/fichas/rubeola': typeof AuthenticatedFichasRubeolaRoute
  '/_authenticated/fichas/sarampo': typeof AuthenticatedFichasSarampoRoute
  '/_authenticated/nova-ficha/chikungunya': typeof AuthenticatedNovaFichaChikungunyaRoute
  '/_authenticated/nova-ficha/coqueluche': typeof AuthenticatedNovaFichaCoquelucheRoute
  '/_authenticated/nova-ficha/dengue': typeof AuthenticatedNovaFichaDengueRoute
  '/_authenticated/nova-ficha/difteria': typeof AuthenticatedNovaFichaDifteriaRoute
  '/_authenticated/nova-ficha/epizootia': typeof AuthenticatedNovaFichaEpizootiaRoute
  '/_authenticated/nova-ficha/febre-amarela': typeof AuthenticatedNovaFichaFebreAmarelaRoute
  '/_authenticated/nova-ficha/rubeola': typeof AuthenticatedNovaFichaRubeolaRoute
  '/_authenticated/nova-ficha/sarampo': typeof AuthenticatedNovaFichaSarampoRoute
  '/_authenticated/fichas/': typeof AuthenticatedFichasIndexRoute
  '/_authenticated/nova-ficha/': typeof AuthenticatedNovaFichaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/painel'
    | '/usuarios'
    | '/fichas/chikungunya'
    | '/fichas/coqueluche'
    | '/fichas/dengue'
    | '/fichas/difteria'
    | '/fichas/epizootia'
    | '/fichas/febre-amarela'
    | '/fichas/rubeola'
    | '/fichas/sarampo'
    | '/nova-ficha/chikungunya'
    | '/nova-ficha/coqueluche'
    | '/nova-ficha/dengue'
    | '/nova-ficha/difteria'
    | '/nova-ficha/epizootia'
    | '/nova-ficha/febre-amarela'
    | '/nova-ficha/rubeola'
    | '/nova-ficha/sarampo'
    | '/fichas/'
    | '/nova-ficha/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/painel'
    | '/usuarios'
    | '/'
    | '/fichas/chikungunya'
    | '/fichas/coqueluche'
    | '/fichas/dengue'
    | '/fichas/difteria'
    | '/fichas/epizootia'
    | '/fichas/febre-amarela'
    | '/fichas/rubeola'
    | '/fichas/sarampo'
    | '/nova-ficha/chikungunya'
    | '/nova-ficha/coqueluche'
    | '/nova-ficha/dengue'
    | '/nova-ficha/difteria'
    | '/nova-ficha/epizootia'
    | '/nova-ficha/febre-amarela'
    | '/nova-ficha/rubeola'
    | '/nova-ficha/sarampo'
    | '/fichas'
    | '/nova-ficha'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/painel'
    | '/_authenticated/usuarios'
    | '/_authenticated/'
    | '/_authenticated/fichas/chikungunya'
    | '/_authenticated/fichas/coqueluche'
    | '/_authenticated/fichas/dengue'
    | '/_authenticated/fichas/difteria'
    | '/_authenticated/fichas/epizootia'
    | '/_authenticated/fichas/febre-amarela'
    | '/_authenticated/fichas/rubeola'
    | '/_authenticated/fichas/sarampo'
    | '/_authenticated/nova-ficha/chikungunya'
    | '/_authenticated/nova-ficha/coqueluche'
    | '/_authenticated/nova-ficha/dengue'
    | '/_authenticated/nova-ficha/difteria'
    | '/_authenticated/nova-ficha/epizootia'
    | '/_authenticated/nova-ficha/febre-amarela'
    | '/_authenticated/nova-ficha/rubeola'
    | '/_authenticated/nova-ficha/sarampo'
    | '/_authenticated/fichas/'
    | '/_authenticated/nova-ficha/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nova-ficha/': {
      id: '/_authenticated/nova-ficha/'
      path: '/nova-ficha'
      fullPath: '/nova-ficha/'
      preLoaderRoute: typeof AuthenticatedNovaFichaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fichas/': {
      id: '/_authenticated/fichas/'
      path: '/fichas'
      fullPath: '/fichas/'
      preLoaderRoute: typeof AuthenticatedFichasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nova-ficha/sarampo': {
      id: '/_authenticated/nova-ficha/sarampo'
      path: '/nova-ficha/sarampo'
      fullPath: '/nova-ficha/sarampo'
      preLoaderRoute: typeof AuthenticatedNovaFichaSarampoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nova-ficha/rubeola': {
      id: '/_authenticated/nova-ficha/rubeola'
      path: '/nova-ficha/rubeola'
      fullPath: '/nova-ficha/rubeola'
      preLoaderRoute: typeof AuthenticatedNovaFichaRubeolaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nova-ficha/febre-amarela': {
      id: '/_authenticated/nova-ficha/febre-amarela'
      path: '/nova-ficha/febre-amarela'
      fullPath: '/nova-ficha/febre-amarela'
      preLoaderRoute: typeof AuthenticatedNovaFichaFebreAmarelaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nova-ficha/epizootia': {
      id: '/_authenticated/nova-ficha/epizootia'
      path: '/nova-ficha/epizootia'
      fullPath: '/nova-ficha/epizootia'
      preLoaderRoute: typeof AuthenticatedNovaFichaEpizootiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nova-ficha/difteria': {
      id: '/_authenticated/nova-ficha/difteria'
      path: '/nova-ficha/difteria'
      fullPath: '/nova-ficha/difteria'
      preLoaderRoute: typeof AuthenticatedNovaFichaDifteriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nova-ficha/dengue': {
      id: '/_authenticated/nova-ficha/dengue'
      path: '/nova-ficha/dengue'
      fullPath: '/nova-ficha/dengue'
      preLoaderRoute: typeof AuthenticatedNovaFichaDengueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nova-ficha/coqueluche': {
      id: '/_authenticated/nova-ficha/coqueluche'
      path: '/nova-ficha/coqueluche'
      fullPath: '/nova-ficha/coqueluche'
      preLoaderRoute: typeof AuthenticatedNovaFichaCoquelucheRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nova-ficha/chikungunya': {
      id: '/_authenticated/nova-ficha/chikungunya'
      path: '/nova-ficha/chikungunya'
      fullPath: '/nova-ficha/chikungunya'
      preLoaderRoute: typeof AuthenticatedNovaFichaChikungunyaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fichas/sarampo': {
      id: '/_authenticated/fichas/sarampo'
      path: '/fichas/sarampo'
      fullPath: '/fichas/sarampo'
      preLoaderRoute: typeof AuthenticatedFichasSarampoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fichas/rubeola': {
      id: '/_authenticated/fichas/rubeola'
      path: '/fichas/rubeola'
      fullPath: '/fichas/rubeola'
      preLoaderRoute: typeof AuthenticatedFichasRubeolaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fichas/febre-amarela': {
      id: '/_authenticated/fichas/febre-amarela'
      path: '/fichas/febre-amarela'
      fullPath: '/fichas/febre-amarela'
      preLoaderRoute: typeof AuthenticatedFichasFebreAmarelaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fichas/epizootia': {
      id: '/_authenticated/fichas/epizootia'
      path: '/fichas/epizootia'
      fullPath: '/fichas/epizootia'
      preLoaderRoute: typeof AuthenticatedFichasEpizootiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fichas/difteria': {
      id: '/_authenticated/fichas/difteria'
      path: '/fichas/difteria'
      fullPath: '/fichas/difteria'
      preLoaderRoute: typeof AuthenticatedFichasDifteriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fichas/dengue': {
      id: '/_authenticated/fichas/dengue'
      path: '/fichas/dengue'
      fullPath: '/fichas/dengue'
      preLoaderRoute: typeof AuthenticatedFichasDengueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fichas/coqueluche': {
      id: '/_authenticated/fichas/coqueluche'
      path: '/fichas/coqueluche'
      fullPath: '/fichas/coqueluche'
      preLoaderRoute: typeof AuthenticatedFichasCoquelucheRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fichas/chikungunya': {
      id: '/_authenticated/fichas/chikungunya'
      path: '/fichas/chikungunya'
      fullPath: '/fichas/chikungunya'
      preLoaderRoute: typeof AuthenticatedFichasChikungunyaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedFichasChikungunyaRoute: typeof AuthenticatedFichasChikungunyaRoute
  AuthenticatedFichasCoquelucheRoute: typeof AuthenticatedFichasCoquelucheRoute
  AuthenticatedFichasDengueRoute: typeof AuthenticatedFichasDengueRoute
  AuthenticatedFichasDifteriaRoute: typeof AuthenticatedFichasDifteriaRoute
  AuthenticatedFichasEpizootiaRoute: typeof AuthenticatedFichasEpizootiaRoute
  AuthenticatedFichasFebreAmarelaRoute: typeof AuthenticatedFichasFebreAmarelaRoute
  AuthenticatedFichasRubeolaRoute: typeof AuthenticatedFichasRubeolaRoute
  AuthenticatedFichasSarampoRoute: typeof AuthenticatedFichasSarampoRoute
  AuthenticatedNovaFichaChikungunyaRoute: typeof AuthenticatedNovaFichaChikungunyaRoute
  AuthenticatedNovaFichaCoquelucheRoute: typeof AuthenticatedNovaFichaCoquelucheRoute
  AuthenticatedNovaFichaDengueRoute: typeof AuthenticatedNovaFichaDengueRoute
  AuthenticatedNovaFichaDifteriaRoute: typeof AuthenticatedNovaFichaDifteriaRoute
  AuthenticatedNovaFichaEpizootiaRoute: typeof AuthenticatedNovaFichaEpizootiaRoute
  AuthenticatedNovaFichaFebreAmarelaRoute: typeof AuthenticatedNovaFichaFebreAmarelaRoute
  AuthenticatedNovaFichaRubeolaRoute: typeof AuthenticatedNovaFichaRubeolaRoute
  AuthenticatedNovaFichaSarampoRoute: typeof AuthenticatedNovaFichaSarampoRoute
  AuthenticatedFichasIndexRoute: typeof AuthenticatedFichasIndexRoute
  AuthenticatedNovaFichaIndexRoute: typeof AuthenticatedNovaFichaIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedFichasChikungunyaRoute: AuthenticatedFichasChikungunyaRoute,
  AuthenticatedFichasCoquelucheRoute: AuthenticatedFichasCoquelucheRoute,
  AuthenticatedFichasDengueRoute: AuthenticatedFichasDengueRoute,
  AuthenticatedFichasDifteriaRoute: AuthenticatedFichasDifteriaRoute,
  AuthenticatedFichasEpizootiaRoute: AuthenticatedFichasEpizootiaRoute,
  AuthenticatedFichasFebreAmarelaRoute: AuthenticatedFichasFebreAmarelaRoute,
  AuthenticatedFichasRubeolaRoute: AuthenticatedFichasRubeolaRoute,
  AuthenticatedFichasSarampoRoute: AuthenticatedFichasSarampoRoute,
  AuthenticatedNovaFichaChikungunyaRoute:
    AuthenticatedNovaFichaChikungunyaRoute,
  AuthenticatedNovaFichaCoquelucheRoute: AuthenticatedNovaFichaCoquelucheRoute,
  AuthenticatedNovaFichaDengueRoute: AuthenticatedNovaFichaDengueRoute,
  AuthenticatedNovaFichaDifteriaRoute: AuthenticatedNovaFichaDifteriaRoute,
  AuthenticatedNovaFichaEpizootiaRoute: AuthenticatedNovaFichaEpizootiaRoute,
  AuthenticatedNovaFichaFebreAmarelaRoute:
    AuthenticatedNovaFichaFebreAmarelaRoute,
  AuthenticatedNovaFichaRubeolaRoute: AuthenticatedNovaFichaRubeolaRoute,
  AuthenticatedNovaFichaSarampoRoute: AuthenticatedNovaFichaSarampoRoute,
  AuthenticatedFichasIndexRoute: AuthenticatedFichasIndexRoute,
  AuthenticatedNovaFichaIndexRoute: AuthenticatedNovaFichaIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
